# Generated by Django 4.2 on 2025-11-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('year_of_study', models.CharField(max_length=20)),
                ('father_income', models.IntegerField()),
                ('family_income', models.IntegerField()),
                ('required_amount', models.IntegerField()),
                ('purpose', models.TextField()),
                ('id_proof', models.FileField(upload_to='loan_docs/id_proof/')),
                ('address_proof', models.FileField(upload_to='loan_docs/address_proof/')),
                ('marksheet_10', models.FileField(upload_to='loan_docs/marksheet_10/')),
                ('marksheet_12', models.FileField(upload_to='loan_docs/marksheet_12/')),
                ('college_id', models.FileField(upload_to='loan_docs/college_id/')),
                ('bank_statement', models.FileField(upload_to='loan_docs/bank_statement/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
