# Generated by Django 4.2 on 2025-11-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='father_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
