# Generated by Django 4.2 on 2025-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan_docs/student_photo/'),
        ),
    ]
